### PR TITLE
DEVOPS-1270: Add a different list of CIDRs for ICMP

### PR DESCRIPTION
**Pull request by cristobal23**
Allow the ability to ping from the office, but not ssh

### CODE REVIEW

**Comment by cristobal23** [comment]
This goes with this [PR to infrastructure](https://github.com/WhistleLabs/infrastructure/pull/272)

**Comment by cristobal23** [comment]
@pickgr Do we intend to have the list of CIDRs that can SSH be the same as the list of CIDRs that can PING?

**Comment by pickgr** [comment]
I wasn't aware of this PR.  Is there a use-case?  It might be a nice improvement, just wondering what's driving this.

**Comment by cristobal23** [comment]
This PR was driven by this [PR](https://github.com/WhistleLabs/infrastructure/pull/272) as noted in the previous comment

**Pull request closed without merging**
